apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: blm1u58bj-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/blm1u58bj-dotnet-basic-gitops